### 搜索
https://service.nickbussok.com/book/search/result
?szInput=万道成神
&nOffset=0
&nLimit=10
&nAuthorNum=1
&szVersion=1

### 详情
https://service.nickbussok.com/bookinfo/book
?nType=1
&aryBookID=14_8685
&nNeedThrdTypeData=1
&szField=nChapterCount,nLastUpdateTime,nOnlineNum,szCopyright,szLastChapter,nSaleStatus,nVersion

### 目录
https://service.nickbussok.com/bookinfo/chapter
?nType=2
&szBookID=14_8685
&nOffset=0
&nLimit=3424
&nSort=1